---

post_max_size: "8M"
upload_max_filesize: "2M"
memory_limit: "256M"
display_errors: "Off"
error_reporting: "E_ALL & ~E_DEPRECATED"
display_startup_errors: "Off"
html_errors: "Off"
track_errors: "Off"
session_bug_compat_warn: "Off"
cgi_fix_pathinfo: "0"

php_ini_settings:
  - option: "memory_limit"
    value: "{{ memory_limit }}"
  - option: "post_max_size"
    value: "{{ post_max_size }}"
  - option: "upload_max_filesize"
    value: "{{ upload_max_filesize }}"
  - option: "display_errors"
    value: "{{ display_errors }}"
  - option: "error_reporting"
    value: "{{ error_reporting }}"
  - option: "display_startup_errors"
    value: "{{ display_startup_errors }}"
  - option: "html_errors"
    value: "{{ html_errors }}"
  - option: "track_errors"
    value: "{{ track_errors }}"
  - option: "session_bug_compat_warn"
    value: "{{ session_bug_compat_warn }}"
  - option: "cgi.fix_pathinfo"
    value: "0"

www_conf_settings:
  - option: "listen"
    value: "/var/run/php-fpm.sock"
  - option: "listen.owner"
    value: "www-data"
  - option: "listen.group"
    value: "www-data"
  - option: "listen.mode"
    value: "0660"
