<?php

define('MATCHES_PER_SLIP', 10);

/**
 * Implements hook_menu()
 */
function quinieleitor_menu() {
  $items = array();
  $items['admin/quinieleitor/add'] = array(
    'title' => 'Add a betting slip',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('quinieleitor_add_betting_slip_form'),
    'access arguments' => array('add betting slips'),
    'file' => 'quinieleitor.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/quinieleitor/resolve'] = array(
    'title' => 'Resolve a betting slip',
    'page callback' => 'quinieleitor_resolve_betting_slip_page',
    'access arguments' => array('resolve betting slips'),
    'file' => 'quinieleitor.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['bet'] = array(
    'title' => 'Bet',
    'page callback' => 'quinieleitor_bet_page',
    'access arguments' => array('bet'),
    'file' => 'quinieleitor.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['hall-of-fame'] = array(
    'title' => 'Hall of Fame',
    'page callback' => 'quinieleitor_hall_of_fame_page',
    'access arguments' => array('bet'),
    'file' => 'quinieleitor.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * Implements hook_perm()
 */
function quinieleitor_perm() {
  return array('add betting slips', 'resolve betting slips', 'bet');
}


function quinieleitor_load_current_slip() {
  $results = db_query('SELECT * FROM {betting_slips} WHERE date>NOW() AND closed=0 ORDER BY date ASC LIMIT 1');
  $slip = db_fetch_object($results);
  if ($slip) {
    $slip->matches = quinieleitor_load_slip_matches($slip->id);
  }

  return $slip;
}


function quinieleitor_load_slip($slip_id) {
  $results = db_query('SELECT * FROM {betting_slips} WHERE id=%d', $slip_id);
  $slip_data = db_fetch_object($results);
  if ($slip_data) {
    $slip = new ResultsSlip($slip_data->id);
    if ($slip_data->closed) {
      $slip->close();
    }
    $matches = quinieleitor_load_slip_matches($slip->getId());
    foreach ($matches as $match_data) {
      $slip->add(new Match($match_data->id, $match_data->name, $match_data->result));
    }

    return $slip;
  }

  return null;
}


function quinieleitor_load_better_slip($uid, $slip_id) {
  $results = db_query('SELECT b.* FROM {bets} b JOIN {matches} m ON b.match_id=m.id WHERE b.user_id=%d AND m.slip_id=%d ORDER BY m.id ASC', $uid, $slip_id);
  $better_slip = new BetterSlip($uid, $slip_id);
  while ($bet = db_fetch_object($results)) {
    $better_slip->add(new Bet($bet->id, $bet->match_id, $bet->prediction));
  }

  return $better_slip;
}


function quinieleitor_load_betting_slips() {
  $slips = array();
  $results = db_query('SELECT * FROM {betting_slips} ORDER BY date ASC');
  while ($slip = db_fetch_object($results)) {
    $slip->matches = quinieleitor_load_slip_matches($slip->id);
    $slips[] = $slip;
  }
  return $slips;
}


function quinieleitor_load_slip_matches($slip_id) {
  $matches = array();
  $results = db_query('SELECT * FROM {matches} WHERE slip_id=%d ORDER BY id ASC', $slip_id);
  while ($match = db_fetch_object($results)) {
    $matches[$match->id] = $match;

  }

  return $matches;
}

function quinieleitor_save_betting_slip($betting_slip) {
  drupal_write_record('betting_slips', $betting_slip);
  foreach ($betting_slip->matches as $match) {
    $match->slip_id = $betting_slip->id;
    drupal_write_record('matches', $match);
  }
}


function quinieleitor_save_bet($bet) {
  foreach ($bet->matches as $match_bet) {
    drupal_write_record('bets', $match_bet);
  }
}


function quinieleitor_resolve_betting_slip($slip_id, $matches) {
  foreach ($matches as $match_id => $result) {
    db_query('UPDATE {matches} set result="%s" WHERE id=%d', $result, $match_id);
  }
  db_query('UPDATE {betting_slips} set closed=1 WHERE id=%d', $slip_id);

  module_invoke_all('betting_slip_resolved', $slip_id);
}


/**
 * Specification of betting_slip_resolved.
 */
function hook_betting_slip_resolved($slip_id)
{
}


/**
 * Implements hook_betting_slip_resolved.
 */
function quinieleitor_betting_slip_resolved($slip_id) {
  $better_slips = quinieleitor_load_all_bets_for_slip($slip_id);

  quinieleitor_update_all_better_points($slip_id, $better_slips);
}


function quinieleitor_load_all_bets_for_slip($slip_id) {
  $better_slips = new BetterSlips();
  $results = db_query('SELECT DISTINCT(b.user_id) FROM {bets} b JOIN {matches} m WHERE b.match_id = m.id AND m.slip_id = %d', $slip_id);
  while ($row = db_fetch_object($results)) {
    $better_slips->add(quinieleitor_load_better_slip($row->user_id, $slip_id));
  }

  return $better_slips;
}


function quinieleitor_update_all_better_points($slip_id, $better_slips) {
  $results_slip = quinieleitor_load_slip($slip_id);
  $calculator = new PrizeCalculator(quinieleitor_get_prize_table());
  $better_slips->calculatePrizes($results_slip, $calculator);
  foreach ($better_slips->all() as $better_slip) {
    quinieleitor_add_better_points($better_slip->getUserId(), $better_slip->getPrize());
  }
}


function quinieleitor_get_prize_table() {
  return array(
    'slip_value' => 100,
    'prizes' => array(
      10 => 0.4,
       9 => 0.2,
       8 => 0.12,
       7 => 0.08,
     ),
  );
}


function quinieleitor_add_better_points($uid, $points) {
  $current_points = quinieleitor_load_better_points($points);
  $score = new stdClass();
  $score->user_id = $uid;
  $score->points = $points + $current_points;
  drupal_write_record('better_points', $score);
}


function quinieleitor_load_better_points($uid) {
  $results = db_query('SELECT points FROM {better_points} WHERE user_id=%d', $uid);
  $row = db_fetch_object($results);

  return $row ? $row->points : 0;
}


function quinieleitor_load_hall_of_fame() {
  $results = db_query('SELECT * FROM {better_points} p JOIN {users} u ON p.user_id=u.uid ORDER BY points DESC');
  $hall_of_fame = array();
  while ($row = db_fetch_object($results)) {
    $hall_of_fame[] = $row;
  }

  return $hall_of_fame;
}


class Bet
{
    private $id;
    private $matchId;
    private $prediction;


    public function __construct($id, $match_id, $prediction)
    {
        $this->id = $id;
        $this->matchId = $match_id;
        $this->prediction = $prediction;
    }

    public function getMatchId()
    {
        return $this->matchId;
    }

    public function hits(Match $match)
    {
        return $match->getResult() == $this->prediction;
    }

    public function getPrediction()
    {
        return $this->prediction;
    }


}

class Match
{
    private $id;
    private $name;
    private $result;

    public function __construct($id, $name, $result = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->result = $result;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getResult()
    {
        return $this->result;
    }

}

class PrizeCalculator
{
    private $prizeTable;

    public function __construct(array $prize_table)
    {
        $this->prizeTable = $prize_table;
    }

    public function calculatePrize($hits, $num_players, $share_with)
    {
      if (isset($this->prizeTable['prizes'][$hits])) {
        return $num_players * $this->prizeTable['slip_value'] * $this->prizeTable['prizes'][$hits] / $share_with;
      }

      return 0;
    }
}


class BetterSlips
{
    private $slips;

    public function __construct(array $slips = array())
    {
        $this->slips = $slips;
    }

    public function add(BetterSlip $slip)
    {
        $this->slips[] = $slip;
    }

    public function all()
    {
        return $this->slips;
    }

    public function calculatePrizes(ResultsSlip $results_slip, PrizeCalculator $calculator)
    {
        $hits_count = $this->getHitsCount($results_slip);
        foreach ($this->slips as $better_slip) {
            $better_slip->calculatePrizeWith($results_slip, $calculator, count($this->slips), $hits_count);
        }
    }

    private function getHitsCount(ResultsSlip $results_slip)
    {
      $hits_count = array();
      foreach ($this->slips as $better_slip) {
        $player_hits = $better_slip->getHits($results_slip);
        if (!isset($hits_count[$player_hits])) {
          $hits_count[$player_hits] = 0;
        }
        $hits_count[$player_hits]++;
      }

      return $hits_count;
    }
}


class ResultsSlip
{
    private $id;
    private $matches = array();
    private $closed = false;

    public function __construct($id = null)
    {
        $this->id = $id;
    }

    public function getId()
    {
        return $this->id;
    }

    public function add(Match $match)
    {
        $this->matches[$match->getId()] = $match;
    }

    public function getMatches()
    {
        return $this->matches;
    }

    public function close()
    {
        $this->closed = true;
    }

    public function isClosed()
    {
        return $this->closed;
    }
}


class BetterSlip
{
    private $userId;
    private $slipId;
    private $bets = array();
    private $prize = 0;

    public function __construct($user_id, $slip_id)
    {
        $this->userId = $user_id;
        $this->slipId = $slip_id;
    }

    public function add(Bet $bet)
    {
        $this->bets[$bet->getMatchId()] = $bet;
    }

    public function calculatePrizeWith(ResultsSlip $results_slip, PrizeCalculator $calculator, $num_slips, array $hits_count)
    {
        $hits = $this->getHits($results_slip);
        $share_with_betters = isset($hits_count[$hits]) ? $hits_count[$hits] : 1;
        $this->prize = $calculator->calculatePrize($hits, $num_slips, $share_with_betters);
    }

    public function getHits(ResultsSlip $results_slip)
    {
        $hits = 0;
        foreach ($results_slip->getMatches() as $match) {
            $hits += $this->bets[$match->getId()]->hits($match);
        }

        return $hits;
    }

    public function getUserId()
    {
        return $this->userId;
    }

    public function getPrize()
    {
        return $this->prize;
    }

    public function getBets()
    {
        return $this->bets;
    }

}
